micronaut:
  application:
    name: emotion-service
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    port: ${EMOTION_SERVICE_PORT:10095}
    context-path: /emotion
r2dbc:
  datasources:
    default:
      db-type: postgres
      dialect: POSTGRES
      url: r2dbc:postgresql://${POSTGRES_HOST_DB:localhost}:${POSTGRES_PORT_DB:5432}/jeri-emotion-service
      username: ${POSTGRES_AUTH_USERNAME:postgres}
      password: ${POSTGRES_AUTH_PASSWORD:123456789}
consul:
  client:
    registration:
      enabled: true
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
elasticsearch.httpHosts: http://${ELASTIC_SEARCH_HOST:localhost}:9200
flyway:
  datasources:
    default:
      enabled: true
      validate-on-migrate: true
      validate-migration-naming: true
      url: jdbc:postgresql://${POSTGRES_HOST_DB:localhost}:${POSTGRES_PORT_DB:5432}/jeri-emotion-service
      username: ${POSTGRES_AUTH_USERNAME:postgres}
      password: ${POSTGRES_AUTH_PASSWORD:123456789}
minio:
  endpoint: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:jeri-emotion-service}
api:
  path:
    category: /api/v1/category