-- V1: init tables on user-service

CREATE TABLE addresses
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted    BOOLEAN   DEFAULT FALSE                 NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()                 NOT NULL,
    updated_at TIMESTAMP DEFAULT NULL,
    version    INTEGER   DEFAULT 0                     NOT NULL,
    address    VARCHAR(50),
    ward       VARCHAR(50),
    city       VARCHAR(50),
    country    VARCHAR(50),
    zip_code   VARCHAR(50),
    CONSTRAINT pk_addresses PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted      BOOLEAN   DEFAULT FALSE                 NOT NULL,
    created_at   TIMESTAMP DEFAULT NOW()                 NOT NULL,
    updated_at   TIMESTAMP DEFAULT NULL,
    version      INTEGER   DEFAULT 0                     NOT NULL,
    code         VARCHAR(30)                             NOT NULL,
    first_name   VARCHAR(50)                             NOT NULL,
    last_name    VARCHAR(50)                             NOT NULL,
    gender       VARCHAR(50)                             NOT NULL,
    birth_date   DATE                                    NOT NULL,
    phone_number VARCHAR(30)                             NOT NULL,
    role_id      VARCHAR(255)                            NOT NULL,
    display_name VARCHAR(100)                            NOT NULL,
    email        VARCHAR(200)                            NOT NULL,
    password     VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_code UNIQUE (code);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);